#!/bin/bash

. ../m1r1_site.sh

SERVER_ID_REPLICA=${TEMPLATE_SERVER_ID_REPLICA_0}
BIND_ADDRESS_REPLICA=${TEMPLATE_BIND_ADDRESS_REPLICA_0}
BIND_ADDRESS_MASTER=${TEMPLATE_BIND_ADDRESS_MASTER_0}

echo "SERVER_ID_REPLICA:" $SERVER_ID_REPLICA
echo "BIND_ADDRESS_REPLICA:" $BIND_ADDRESS_REPLICA
echo "BIND_ADDRESS_MASTER:" $BIND_ADDRESS_MASTER

python3 ../ha_template.py \
    --infile ../config/replica_mysqld.TEMPLATE.cnf \
    --outfile replica_mysqld.GENERATED.cnf \
    --TEMPLATE_SERVER_ID ${SERVER_ID_REPLICA} \
    --TEMPLATE_BIND_ADDRESS ${BIND_ADDRESS_REPLICA} \
    --TEMPLATE_BIND_ADDRESS_MASTER ${BIND_ADDRESS_MASTER}