. ../m1r1_site.sh

SERVER_ID_MASTER=${TEMPLATE_SERVER_ID_MASTER_0}
BIND_ADDRESS_MASTER=${TEMPLATE_BIND_ADDRESS_MASTER_0}

echo "SERVER_ID_MASTER:" $SERVER_ID_MASTER
echo "BIND_ADDRESS_MASTER:" $BIND_ADDRESS_MASTER

python3 ../ha_template.py \
    --infile ../config/master_mysqld.TEMPLATE.cnf \
    --outfile master_mysqld.GENERATED.cnf \
    --TEMPLATE_SERVER_ID ${SERVER_ID_MASTER} \
    --TEMPLATE_BIND_ADDRESS ${BIND_ADDRESS_MASTER} \
    --TEMPLATE_BIND_ADDRESS_MASTER ${BIND_ADDRESS_MASTER}

